### ISSUE TITLE
Error `Can't get response from "XX.XXX.XX:XXXXX", socket timed out` 

### ISSUE THREAD

**Issue by crashzk** [GAMMACASE/ServerRedirect#48] opened 2023-09-16 21:41 UTC
I'm getting the following errors on my servers:
```
L 09/16/2023 - 18:39:03: [server_redirect.smx] [Server Redirect] Can't get response from "XX.XXX.XX:XXXXX", socket timed out.

L 09/16/2023 - 18:39:03: [server_redirect.smx] [Server Redirect] Can't get response from "XX.XXX.XX:XXXXX", socket timed out.

L 09/16/2023 - 18:39:03: [server_redirect.smx] [Server Redirect] Can't get response from "XX.XXX.XX:XXXXX", socket timed out.

L 09/16/2023 - 18:39:03: [server_redirect.smx] [Server Redirect] Can't get response from "XX.XXX.XX:XXXXX", socket timed out.

L 09/16/2023 - 18:39:03: [server_redirect.smx] [Server Redirect] Can't get response from "XX.XXX.XX:XXXXX", socket timed out.
```

**Comment by GAMMACASE** [comment] 2023-09-17 10:10
It means that the server haven't got any A2S reply from the target ip, it's not a plugin problem, make sure the target server as pingable from the destination you are sending the A2S requests. Also you can use ``server_redirect_log_if_server_is_unavailable 0`` to disable these log messages, but that won't fix anything, only hide them.

**Closed as completed by GAMMACASE** 2023-09-17 10:10 UTC

**Comment by crashzk** [comment] 2023-09-17 12:03
I understand, could this cause some type of operating error? In the tests I did here I can still connect to the servers through the plugin, it only shows these messages in the console but without harmful errors.

**Comment by GAMMACASE** [comment] 2023-09-17 14:18
These are more of a informative logging messages, and you should understand them as "Server didn't reply to the query in the set time", the cause of why that happened is dependent on the setup environment you have, so it's almost impossible to tell why that happened by just that log alone.
One more reason why that could happen if the server replies slow to these queries, for example default timeout value is 10 seconds, when if server doesn't reply in time the log message would be printed. It's defined as ``server_redirect_socket_timeout`` cvar, but edit with caution, as it may only degrade overall performance.

**Comment by tslashd** [comment] 2023-09-17 14:23
`host_info_show 0` I believe causes the server to NOT respond to A2S queries.

@crashzk can you make sure the server that is not responding has that value set to `1` ?

**Comment by crashzk** [comment] 2023-09-17 14:30
> `host_info_show 0` I believe causes the server to NOT respond to A2S queries.
> 
> @crashzk can you make sure the server that is not responding has that value set to `1` ?

![image](https://github.com/GAMMACASE/ServerRedirect/assets/32937653/dcb3d13b-dc1d-4282-b342-682cbefb7eaa)
