### ISSUE TITLE
Client is not connected

### ISSUE THREAD

**Issue by Septembers** [GAMMACASE/ServerRedirect#13] opened 2020-04-15 20:45 UTC
last version

L 04/15/2020 - 20:07:35: [SM] Exception reported: Client 14 is not connected
L 04/15/2020 - 20:07:35: [SM] Blaming: redirect/server_redirect.smx
L 04/15/2020 - 20:07:35: [SM] Call stack trace:
L 04/15/2020 - 20:07:35: [SM]   [0] GetClientUserId
L 04/15/2020 - 20:07:35: [SM]   [1] Line 806, C:\Users\September-PC\Desktop\COMPILE 1.10\server_redirect.sp::ServerInfo_Menu

**Comment by GAMMACASE** [comment] 2020-04-21 21:05
I guess this can be closed, reopen this if this issue will happen again. Also wasn't really able to reproduce it, looks like a super edge case situation, but anyway should be fixed now.

**Closed as completed by GAMMACASE** 2020-04-21 21:05 UTC
Labels: bug
