### ISSUE TITLE
Add gamedata for CS:S

### ISSUE THREAD

**Issue by SkleKng** [GAMMACASE/ServerRedirect#46] opened 2023-01-09 05:48 UTC
Currently, the gamedata only supports offsets for CS:GO. It would be great to add support for CS:S as well as other Source games.

**Comment by GAMMACASE** [comment] 2023-01-09 13:53
Duplicate of https://github.com/GAMMACASE/ServerRedirect/issues/35

**Closed as completed by GAMMACASE** 2023-01-09 13:53 UTC
